# Generated by Django 5.2.10 on 2026-04-21 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MsjConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_telefono', models.CharField(max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('visita_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('ultimo_mensaje_fecha', models.DateTimeField(blank=True, null=True)),
                ('no_leidos', models.IntegerField(default=0)),
                ('fecha_ventana_24h', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'msj_conversacion',
                'ordering': ['-ultimo_mensaje_fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MsjMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('template', 'Plantilla'), ('audio', 'Audio'), ('documento', 'Documento'), ('ubicacion', 'Ubicación')], default='texto', max_length=20)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('media_caption', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.msjconversacion')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'msj_mensaje',
                'ordering': ['id'],
            },
        ),
    ]
