# Generated by Django 5.2.10 on 2026-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msjconversacion',
            name='requiere_apoyo',
            field=models.BooleanField(default=False),
        ),
    ]
