# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='cita_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='cita_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
