# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0002_rutvisita_cita_inicio_rutvisita_cita_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='cita_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='cita_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
