# Generated by Django 5.2.10 on 2026-03-19 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_gen_api_key'),
        ('ruteo', '0003_alter_rutvisita_cita_inicio_cita_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_api_key_rel', to='general.genapikey'),
        ),
    ]
