# Generated by Django 5.2.10 on 2026-03-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0003_alter_rutvisita_cita_inicio_cita_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='cita_tipo',
            field=models.CharField(blank=True, choices=[('obligatoria', 'Obligatoria'), ('preferente', 'Preferente')], max_length=20, null=True),
        ),
    ]
