# Generated by Django 5.2.10 on 2026-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0005_merge_20260330_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
