# Generated by Django 5.2.10 on 2026-04-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0006_agregar_observacion_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='destinatario_direccion_complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
