# Generated by Django 5.2.10 on 2026-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0007_agregar_direccion_complemento_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('despacho_id', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('estado_enviado', models.BooleanField(default=False)),
                ('tipo', models.CharField(default='whatsapp', max_length=20)),
            ],
            options={
                'db_table': 'rut_notificacion',
                'ordering': ['-id'],
            },
        ),
    ]
