# Generated by Django 5.2.10 on 2026-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0009_crear_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='tarifa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
