# Generated by Django 5.2.10 on 2026-05-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0010_agregar_tarifa_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='despacho_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_despacho_anterior_rel', to='ruteo.rutdespacho'),
        ),
    ]
