# Generated by Django 5.2.10 on 2026-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0011_rutvisita_despacho_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='conductor_id',
            field=models.IntegerField(null=True),
        ),
    ]
