# Generated by Django 5.2.10 on 2026-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0012_rutdespacho_conductor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='entrega_complemento_intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
