# Generated by Django 5.2.10 on 2026-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0013_rutvisita_entrega_complemento_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutnovedad',
            name='nuevo_complemento_intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
