# Generated by Django 5.2.10 on 2026-08-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0014_rutnovedad_nuevo_complemento_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutTerminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField()),
                ('usuario_id', models.IntegerField(null=True)),
                ('placa', models.CharField(max_length=20, null=True)),
                ('conductor_nombre', models.CharField(max_length=255, null=True)),
                ('fecha_viaje', models.DateTimeField(null=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('total_guias', models.IntegerField(default=0)),
                ('entregadas', models.IntegerField(default=0)),
                ('con_novedad', models.IntegerField(default=0)),
                ('porcentaje', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminaciones', to='ruteo.rutdespacho')),
            ],
            options={
                'db_table': 'rut_terminacion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RutTerminacionNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('destinatario', models.CharField(max_length=150, null=True)),
                ('tipo_novedad', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('terminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='ruteo.rutterminacion')),
            ],
            options={
                'db_table': 'rut_terminacion_novedad',
                'ordering': ['id'],
            },
        ),
    ]
