# Generated by Django 5.2.10 on 2026-08-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0015_rutterminacion_rutterminacionnovedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutterminacion',
            name='agencia',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
