# Generated by Django 5.2.10 on 2026-08-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0016_rutterminacion_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutAgenteSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50)),
                ('conductor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='activa', max_length=10)),
                ('historial', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_sesiones', to='ruteo.rutdespacho')),
            ],
            options={
                'indexes': [models.Index(fields=['telefono', 'estado'], name='ruteo_rutag_telefon_34827c_idx')],
            },
        ),
    ]
