# Generated by Django 5.2.10 on 2026-08-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0017_rutagentesesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='conductor_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
