# Generated by Django 5.2.10 on 2026-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0018_rutdespacho_conductor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutagentesesion',
            name='contexto',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rutagentesesion',
            name='paso',
            field=models.CharField(default='menu', max_length=20),
        ),
    ]
