# Generated by Django 5.2.10 on 2026-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0019_rutagentesesion_contexto_rutagentesesion_paso'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='cargado_en',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rutdespacho',
            name='cargado_por_id',
            field=models.IntegerField(null=True),
        ),
    ]
