# Generated by Django 5.2.10 on 2026-09-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0020_rutdespacho_cargado_en_rutdespacho_cargado_por_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='entregado_por_id',
            field=models.IntegerField(null=True),
        ),
    ]
