# Generated by Django 5.2.10 on 2026-03-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerEntregaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita_id', models.IntegerField()),
                ('numero', models.IntegerField(null=True)),
                ('documento', models.CharField(max_length=30, null=True)),
                ('destinatario', models.CharField(max_length=150, null=True)),
                ('destinatario_direccion', models.CharField(default='', max_length=200)),
                ('destinatario_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('unidades', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='vertical.verentrega')),
            ],
            options={
                'db_table': 'ver_entrega_detalle',
                'ordering': ['orden'],
            },
        ),
    ]
