# Generated by Django 5.2.10 on 2026-01-22 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_tipo_id', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=100)),
                ('tamano', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('almacenamiento_id', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=100, null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'gen_archivo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=20, null=True)),
                ('longitud', models.CharField(max_length=20, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenComplemento',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('instalado', models.BooleanField(default=False)),
                ('estructura_json', models.JSONField(null=True)),
                ('datos_json', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'gen_complemento',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_estado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_pais',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenEmpresa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('imagen', models.TextField(null=True)),
                ('contenedor_id', models.IntegerField()),
                ('rededoc_id', models.IntegerField(null=True)),
                ('subdominio', models.CharField(default='demo', max_length=100)),
                ('asistente_electronico', models.BooleanField(default=False)),
                ('asistente_predeterminado', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genciudad')),
            ],
            options={
                'db_table': 'gen_empresa',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenConfiguracion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('informacion_factura', models.TextField(null=True)),
                ('informacion_factura_superior', models.TextField(null=True)),
                ('gen_uvt', models.DecimalField(decimal_places=6, default=49799, max_digits=20)),
                ('gen_emitir_automaticamente', models.BooleanField(default=False)),
                ('rut_sincronizar_complemento', models.BooleanField(default=False)),
                ('rut_decodificar_direcciones', models.BooleanField(default=True)),
                ('rut_rutear_franja', models.BooleanField(default=False)),
                ('rut_direccion_origen', models.TextField(null=True)),
                ('rut_latitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('rut_longitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('tte_usuario_rndc', models.CharField(max_length=50, null=True)),
                ('tte_clave_rndc', models.CharField(max_length=50, null=True)),
                ('tte_numero_poliza', models.CharField(max_length=50, null=True)),
                ('tte_fecha_vence_poliza', models.DateField(null=True)),
                ('tte_numero_identificacion_aseguradora', models.CharField(max_length=50, null=True)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.genempresa')),
            ],
            options={
                'db_table': 'gen_configuracion',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='genciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genestado'),
        ),
        migrations.AddField(
            model_name='genestado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genpais'),
        ),
    ]
