# Generated by Django 5.2.10 on 2026-01-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genempresa',
            name='asistente_electronico',
        ),
        migrations.RemoveField(
            model_name='genempresa',
            name='asistente_predeterminado',
        ),
        migrations.RemoveField(
            model_name='genempresa',
            name='rededoc_id',
        ),
    ]
