# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_genempresa_asistente_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_hora_inicio',
            field=models.TimeField(default='07:00', null=True),
        ),
    ]
