# Generated by Django 5.2.10 on 2026-03-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_genconfiguracion_rut_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gen_api_key',
            },
        ),
    ]
