# Generated by Django 5.2.10 on 2026-03-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_genconfiguracion_rut_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_cita_tipo_defecto',
            field=models.CharField(choices=[('obligatoria', 'Obligatoria'), ('preferente', 'Preferente')], default='obligatoria', max_length=20),
        ),
    ]
