# Generated by Django 5.2.10 on 2026-03-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_cita_tipo_ventanas_entrega'),
        ('general', '0004_gen_api_key'),
    ]

    operations = [
    ]
