# Generated by Django 5.2.10 on 2026-04-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_merge_20260330_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_whatsapp_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
