# Generated by Django 5.2.10 on 2026-04-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_agregar_whatsapp_habilitado_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_estrategia_ruteo',
            field=models.CharField(choices=[('distancia', 'Ruta más corta'), ('tiempo', 'Menor tiempo'), ('balanceado', 'Balanceado')], default='balanceado', max_length=20),
        ),
    ]
