# Generated by Django 5.2.10 on 2026-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_agregar_limite_importacion_intervalo_alertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_whatsapp_plantilla_despacho',
            field=models.CharField(blank=True, help_text='Nombre de la plantilla aprobada en Meta para notificar despachos. Default: variable de entorno META_PLANTILLA_DESPACHO.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_whatsapp_plantilla_idioma',
            field=models.CharField(blank=True, default='es', help_text='Codigo de idioma de la plantilla (es, en_US, etc.)', max_length=10),
        ),
    ]
