# Generated by Django 5.2.10 on 2026-01-22 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'ctn_ciudad',
            },
        ),
        migrations.CreateModel(
            name='CtnEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'ctn_estado',
            },
        ),
        migrations.CreateModel(
            name='CtnPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'ctn_pais',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.EmailField(max_length=255, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('apellido', models.CharField(max_length=255, null=True)),
                ('nombre_corto', models.CharField(max_length=255, null=True)),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('empresa_nombre', models.CharField(max_length=255, null=True)),
                ('empresa_numero_identificacion', models.CharField(max_length=20, null=True)),
                ('cargo', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('idioma', models.CharField(default='es', max_length=2)),
                ('imagen', models.TextField(null=True)),
                ('imagen_thumbnail', models.TextField(null=True)),
                ('vr_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_abono', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fecha_limite_pago', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('cortesia', models.BooleanField(default=False)),
                ('es_socio', models.BooleanField(default=False)),
                ('es_administrador', models.BooleanField(default=False)),
                ('socio_id', models.IntegerField(null=True)),
                ('operacion_id', models.IntegerField(null=True)),
                ('operacion_cargo_id', models.IntegerField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('aplicacion', models.CharField(max_length=10, null=True)),
                ('dominio', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='CtnContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('numero_identificacion', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_conexion', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen', models.TextField(null=True)),
                ('usuarios', models.IntegerField(default=1)),
                ('reddoc', models.BooleanField(default=False)),
                ('ruteo', models.BooleanField(default=False)),
                ('cortesia', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ctn_contenedor',
            },
        ),
        migrations.CreateModel(
            name='CtnDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('direccion', models.CharField(max_length=200)),
                ('direccion_formato', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('cantidad_resultados', models.IntegerField(default=0)),
                ('resultados', models.JSONField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenedor.ctnciudad')),
            ],
            options={
                'db_table': 'ctn_direccion',
            },
        ),
        migrations.CreateModel(
            name='CtnDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='contenedor.ctncontenedor')),
            ],
            options={
                'db_table': 'ctn_dominio',
            },
        ),
        migrations.AddField(
            model_name='ctnciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnestado'),
        ),
        migrations.AddField(
            model_name='ctnestado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnpais'),
        ),
        migrations.CreateModel(
            name='UsuarioContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctncontenedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ctn_usuario_contenedor',
                'unique_together': {('usuario', 'contenedor')},
            },
        ),
    ]
