# Generated by Django 5.2.10 on 2026-01-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctncontenedor',
            name='cortesia',
        ),
        migrations.RemoveField(
            model_name='ctncontenedor',
            name='numero_identificacion',
        ),
        migrations.RemoveField(
            model_name='ctncontenedor',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='ctncontenedor',
            name='reddoc',
        ),
        migrations.RemoveField(
            model_name='ctncontenedor',
            name='ruteo',
        ),
        migrations.RemoveField(
            model_name='ctncontenedor',
            name='usuario',
        ),
    ]
