# Generated by Django 5.2.10 on 2026-01-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0002_remove_ctncontenedor_cortesia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CtnContenedor',
            new_name='Contenedor',
        ),
        migrations.RenameModel(
            old_name='CtnDominio',
            new_name='Dominio',
        ),
    ]
