# Generated by Django 5.2.10 on 2026-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0003_rename_ctncontenedor_contenedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(null=True)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=50)),
                ('estado_usado', models.BooleanField(default=False)),
                ('vence', models.DateField(null=True)),
                ('accion', models.CharField(default='registro', max_length=10)),
                ('usuario_invitado_username', models.EmailField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'ctn_verificacion',
            },
        ),
    ]
