# Generated by Django 5.2.10 on 2026-01-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0004_ctnverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
