# Generated by Django 5.2.10 on 2026-04-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0005_contenedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='acceso_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
