# Generated by Django 5.2.10 on 2026-04-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0006_agregar_acceso_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnWhatsappConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=50, unique=True)),
                ('waba_id', models.CharField(max_length=50)),
                ('display_phone_number', models.CharField(max_length=30, null=True)),
                ('verified_name', models.CharField(max_length=100, null=True)),
                ('access_token_cifrado', models.TextField()),
                ('app_secret_cifrado', models.TextField(null=True)),
                ('verify_token', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('fecha_conexion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('contenedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conexion', to='contenedor.contenedor')),
            ],
            options={
                'db_table': 'ctn_whatsapp_conexion',
            },
        ),
    ]
