# Generated by Django 5.2.10 on 2026-04-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0007_ctnwhatsappconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='acceso_whatsapp_notificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
