# Generated by Django 5.2.10 on 2026-04-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0008_contenedor_acceso_whatsapp_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocontenedor',
            name='perfil_movil',
            field=models.CharField(blank=True, choices=[('conductor', 'Conductor'), ('coordinador', 'Coordinador')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuariocontenedor',
            name='perfil_web',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('supervisor', 'Supervisor'), ('consulta', 'Consulta')], default='operativo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuariocontenedor',
            name='tiene_acceso_movil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariocontenedor',
            name='tiene_acceso_web',
            field=models.BooleanField(default=True),
        ),
    ]
