# Generated by Django 5.2.10 on 2026-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0012_poblar_permisos_desde_perfil_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado_registro',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobacion'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=10),
        ),
    ]
